# Site settings
title: liu donghao's blog
email: liu1984567@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here.
url: "https://liu1984567.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  liu1984567


# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
